#server
server: 
    host: 0.0.0.0
    port: 8567


# redis
redis:
    host: 192.168.2.157
    port: 6379
    auth: 

mysql:
  master:
    host: 192.168.2.157
    port: 3306
    user: root
    pass: root
    db:   test
    maxIdleConns: 10
    maxOpenConns: 100
  slaver:
    host: 192.168.2.157
    port: 3306
    user: root
    pass: root
    db:   test
    maxIdleConns: 10
    maxOpenConns: 100
